### ISSUE TITLE
Allow basic query param configuration

### ISSUE THREAD

**Issue by GusAntoniassi** [GusAntoniassi/prometheus-html-exporter#6]
As an alternative to the config file, allow configuration of a "clean" exporter that will receive its configs from Prometheus itself (through URL query params), the same way [blackbox exporter](https://github.com/prometheus/blackbox_exporter#prometheus-configuration) does it.

With this configuration, only a single exporter `scrape_config` will be supported, since Prometheus' scrape_config `params` section allows only strings or string arrays. There may be multiple endpoints but they all will be scraped with the same XPath query, for instance. Still, this should cover a couple of use cases and might make the exporter configuration easier.

Sample Prometheus config with this implementation:
```yaml
scrape_configs:
  - job_name: 'wikipedia-exporter'
    metrics_path: /probe
    params:
      selector: "//div[@id='mw-content-text']//tr[@class='mw-statistics-articles']/td[@class='mw-statistics-numbers']/text()"
      decimal_point_separator: ","
      thousands_separator: " "
      metric_name: wikipedia_articles_total
      metric_type: gauge
      metric_help: "Total of articles available at Wikipedia"
    static_configs:
      - targets:
        - https://fr.wikipedia.org/wiki/Special:Statistics
        - https://pt.wikipedia.org/wiki/Especial:Estat%C3%ADsticas
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9883  # The html-exporter's real hostname:port.
```

Note that in this configuration we lose the ability to configure labels and individual decimal and thousands separators.
